// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLCustomerSegmentML.Model
{
    public class ModelInput
    {
        [ColumnName("CustomerID"), LoadColumn(0)]
        public float CustomerID { get; set; }


        [ColumnName("Gender"), LoadColumn(1)]
        public string Gender { get; set; }


        [ColumnName("Age"), LoadColumn(2)]
        public float Age { get; set; }


        [ColumnName("Annual Income (k$)"), LoadColumn(3)]
        public float Annual_Income__k__ { get; set; }


        [ColumnName("Spending Score (1-100)"), LoadColumn(4)]
        public float Spending_Score__1_100_ { get; set; }


    }
}
